name: Update WordPress

on:
  push:
    paths:
      - 'update_wordpress.sh'  

jobs:
  update-wordpress:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.TEST_SECRET }}

    - name: Copy update script to server
      run: scp -o StrictHostKeyChecking=no ./update_wordpress.sh admin@51.92.221.242:/home/admin/update_wordpress.sh

    - name: Run update script on server
      run: ssh -o StrictHostKeyChecking=no admin@51.92.221.242 'bash /home/admin/update_wordpress.sh'

    - name: Check update status
      id: check_update
      run: |
        ssh -o StrictHostKeyChecking=no admin@51.92.221.242 'bash /home/admin/update_wordpress.sh'
        if [ $? -eq 0 ]; then
          echo "status=ok" >> $GITHUB_ENV
        else
          echo "status=fail" >> $GITHUB_ENV
          exit 1
        fi
